import { Link } from 'react-router-dom'
import { Card } from '@/components/ui/Card'
import { Badge } from '@/components/ui/Badge'
import { Pencil, Trash } from '@/components/ui/icons'
import { cn } from '@/lib/cn'
import { formatMoney, formatDate } from '@/lib/format'
import type { BazarFundingSource, ContributionSourceType } from '@/lib/api/types'

export interface LedgerEntryView {
  id: string
  date: string
  amount: number
  currency: string
  note: string | null
  status: 'Active' | 'Cancelled'
  /** Bazar entries only. */
  fundingSource?: BazarFundingSource
  linkedContributionId?: string | null
  /** Contributions only. */
  sourceType?: ContributionSourceType
  sourceBazarPurchaseId?: string | null
}

export function LedgerEntryCard({
  entry,
  byName,
  recordedByName,
  canEdit,
  onEdit,
  onCancel,
  householdId,
}: {
  entry: LedgerEntryView
  byName: string
  /** The actual submitter's name, passed only when it differs from `byName` (an on-behalf-of entry). */
  recordedByName?: string
  canEdit: boolean
  onEdit: () => void
  onCancel: () => void
  /** Needed to link a Bazar entry to its mirrored contribution, or vice versa. */
  householdId?: string
}) {
  const cancelled = entry.status === 'Cancelled'
  const isLeftover = entry.amount < 0
  const autoGenerated = entry.sourceType === 'AutoFromBazar'

  return (
    <Card className={cn('flex items-center gap-3 p-4', cancelled && 'opacity-50', isLeftover && !cancelled && 'border-primary/40 bg-primary-soft/30')}>
      <div className="min-w-0 flex-1">
        <div className="flex items-center gap-2">
          <p className={cn('font-medium text-ink', cancelled && 'line-through', isLeftover && !cancelled && 'text-primary')}>
            {formatMoney(entry.amount, entry.currency)}
          </p>
          {isLeftover && !cancelled && <Badge tone="primary">Leftover</Badge>}
          {entry.fundingSource && (
            <Badge tone={entry.fundingSource === 'HouseholdFund' ? 'primary' : 'muted'}>
              {entry.fundingSource === 'HouseholdFund' ? 'From household fund' : 'Personal'}
            </Badge>
          )}
          {cancelled && <Badge tone="danger">Cancelled</Badge>}
        </div>
        <p className="truncate text-xs text-muted">
          {formatDate(entry.date)} · {byName}
          {recordedByName && ` · Recorded by ${recordedByName}`}
          {entry.note && ` · ${entry.note}`}
        </p>
        {entry.linkedContributionId && householdId && (
          <Link to={`/h/${householdId}/ledger/contributions`} className="text-xs text-primary hover:underline">
            View linked contribution
          </Link>
        )}
        {autoGenerated && (
          <p className="mt-0.5 text-xs text-muted">
            Auto-generated from a Bazar purchase.
            {entry.sourceBazarPurchaseId && householdId && (
              <>
                {' '}
                <Link to={`/h/${householdId}/ledger/bazar`} className="text-primary hover:underline">
                  View purchase
                </Link>
              </>
            )}
          </p>
        )}
      </div>
      {canEdit && !cancelled && (
        <div className="flex shrink-0 gap-1">
          <button onClick={onEdit} aria-label="Edit" className="rounded-pill p-3 text-muted hover:bg-surface-muted hover:text-ink">
            <Pencil width={16} height={16} />
          </button>
          <button onClick={onCancel} aria-label="Cancel entry" className="rounded-pill p-3 text-muted hover:bg-danger-soft hover:text-danger">
            <Trash width={16} height={16} />
          </button>
        </div>
      )}
    </Card>
  )
}
